sudo: false
language: python

branches:
  only:
    - master

before_install:
  - pip install --upgrade pip setuptools wheel

matrix:
  include:
  - os: linux
    env: NAME=pylint
    python: "3.5.2"
    install:
      - cat tools/conf/pip-list-dev-tools.txt | grep pylint | xargs pip install
    script: tools/pylint