sudo: false
language: python

cache:
  directories:
    - .benchmarks

branches:
  only:
    - master

before_install:
  - pip install --upgrade pip setuptools wheel

matrix:
  include:
  - os: linux
    env: NAME=pylint
    python: "3.6"
    install:
      - pip install -r requirements.txt
    script: pytest --benchmark-autosave --benchmark-only && cd cd .benchmarks/Linux-CPython-3.6-64bit && ls